server:
  port: 1001
  context-path: /

mybatis:
  typeAliasesPackage:
  mapperLocations: classpath:mapper/*.xml

http:
  encoding.charset: UTF-8
  encoding.enable: true
  encoding.force: true

# 数据源配置
spring:
  application: 
    name: yijieyi-demo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: mysql123
  redis:
        host: 47.99.145.73
        port: 9527
        timeout: 20000
        cluster:
            nodes: 47.99.145.73:9001,47.99.145.73:9002,47.99.145.73:9003,47.99.145.73:9004,47.99.145.73:9005,47.99.145.73:9006
            maxRedirects: 6
        pool:
            max-active: 8
            min-idle: 0
            max-idle: 8
            max-wait: -1
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
    
eureka:
  instance:
    hostname: localhost  #eureka客户端主机实例名称
    appname: yijieyi-demo #客户端服务名
    instance-id: yijieyi-demo:1001 #客户端实例名称
    prefer-ip-address: true #显示IP
  client: 
    service-url: 
      # 单机
      #defaultZone: http://localhost:2001/eureka   #把服务注册到eureka注册中心
      defaultZone: http://eureka2001.marry.com:2001/eureka/,http://eureka2002.marry.com:2002/eureka/# 集群
      
info: 
   groupId: $project.groupId$
   artifactId: $project.artifactId$
   version: $project.version$
   负责人: demo
   联系电话: 666
